#!/bin/sh
# phaneslight-template v3.7.2 doc-index
# Regenerates every _index.md under the documentation tree (archive/ excluded). SOLE WRITER of
# indexes; hand-editing them is forbidden. Each entry is extracted in fallback order: DOC header
# line, then first heading, then humanized filename. Entries are ordered by FILENAME, ordinal,
# descending (v3.6.1, was modification time), so a sequenced folder's newest entry is its first
# line and editing an old document does not reorder the index. Rotates an index past ~100 entries:
# the first entries stay inline, the rest collapse into a range line pointing to a frozen
# _index_archive.md. Always exits 0.
INLINE=100

find_root() {
  d=$(pwd)
  while [ -n "$d" ] && [ "$d" != "/" ]; do
    [ -f "$d/.phaneslight/config.json" ] && { printf '%s' "$d"; return 0; }
    d=$(dirname "$d")
  done
  [ -f "/.phaneslight/config.json" ] && { printf '%s' "/"; return 0; }
  return 1
}

cfg_str() {
  grep -o "\"$1\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$2" 2>/dev/null | head -1 \
    | sed 's/.*:[[:space:]]*"\(.*\)"$/\1/'
}

cfg_arr() { # cfg_arr KEY FILE -> newline-separated values
  tr '\n' ' ' < "$2" 2>/dev/null \
    | sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\[\([^]]*\)\].*/\1/p" \
    | grep -o '"[^"]*"' | sed 's/"//g'
}

norm_entries() { # norm_entries DOCROOT  (reads raw entries on stdin)
  while IFS= read -r e; do
    [ -n "$e" ] || continue
    e=$(printf '%s' "$e" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
    [ -n "$e" ] || continue
    e=$(printf '%s' "$e" | tr '\\' '/' | sed 's#^/*##; s#/*$##')
    case "$e" in
      "$1"/*) e=${e#"$1"/} ;;
    esac
    [ -n "$e" ] && printf '%s\n' "$e"
  done
}

is_listed() { # is_listed REL LIST
  _rel=$1
  printf '%s\n' "$2" | while IFS= read -r e; do
    [ -n "$e" ] || continue
    case "$e" in
      */*) case "$_rel" in "$e"|"$e"/*) echo hit ;; esac ;;
      *)   case "/$_rel/" in *"/$e/"*) echo hit ;; esac ;;
    esac
  done | grep -q hit
}

root=$(find_root) || { echo "doc-index: .phaneslight/config.json not found from this directory" >&2; exit 0; }
docRoot=$(cfg_str docRoot "$root/.phaneslight/config.json"); [ -z "$docRoot" ] && docRoot=documentation
# A trailing slash in docRoot would otherwise leak into every derived path and message
# (an empty basename, doubled separators, and absolute paths where relative ones belong).
while [ "${docRoot%/}" != "$docRoot" ]; do docRoot=${docRoot%/}; done
[ -z "$docRoot" ] && docRoot=documentation
docPath="$root/$docRoot"
[ -d "$docPath" ] || { echo "doc-index: no documentation tree"; exit 0; }

doc_line() { # doc_line FILE
  f=$1
  d=$(grep -o '<!--[[:space:]]*DOC[[:space:]]*|[[:space:]]*[^>]*-->' "$f" 2>/dev/null | head -1 \
    | sed 's/<!--[[:space:]]*DOC[[:space:]]*|[[:space:]]*//; s/[[:space:]]*-->.*//')
  if [ -n "$d" ]; then printf '%s' "$d"; return; fi
  h=$(grep -m1 -E '^#{1,6}[[:space:]]' "$f" 2>/dev/null | sed -E 's/^#{1,6}[[:space:]]*//')
  if [ -n "$h" ]; then printf '%s' "$h"; return; fi
  basename "$f" .md | tr -- '-_' '  '
}

exclusions=$(cfg_arr index_exclusions "$root/.phaneslight/config.json" | norm_entries "$docRoot")

countfile=$(mktemp)
echo 0 > "$countfile"

find "$docPath" -type d ! -path '*/archive' ! -path '*/archive/*' | while IFS= read -r folder; do
  name=$(basename "$folder")
  rel=${folder#"$docPath"}
  rel=$(printf '%s' "$rel" | sed 's#^/*##')
  if [ -n "$exclusions" ] && [ -n "$rel" ] && is_listed "$rel" "$exclusions"; then continue; fi
  idx="$folder/_index.md"
  tmp=$(mktemp)
  printf '<!-- GENERATED by phaneslight doc-index. Do not hand-edit. -->\n# Index: %s\n\n' "$name" > "$tmp"

  # Subfolders (excluding archive), sorted by name to match Windows' Sort-Object Name.
  for sf in "$folder"/*/; do
    [ -d "$sf" ] || continue
    sfn=$(basename "$sf")
    [ "$sfn" = "archive" ] && continue
    printf '%s\n' "$sfn"
  done | sort | while IFS= read -r sfn; do
    # An excluded subtree never gets an _index.md (the exclusion check above skips its own
    # index-generation pass entirely), so linking to one here would point at a file that can
    # never exist. Apply the same test the generation path uses.
    if [ -n "$rel" ]; then sfrel="$rel/$sfn"; else sfrel=$sfn; fi
    if [ -n "$exclusions" ] && is_listed "$sfrel" "$exclusions"; then continue; fi
    printf -- '- %s/ : subfolder (see %s/_index.md)\n' "$sfn" "$sfn" >> "$tmp"
  done

  # Markdown files (excluding generated indexes), ordered by FILENAME, ordinal, descending
  # (v3.6.1). The old key was `ls -t`, modification time, which broke the index in the two ways
  # an index must not break. It could not answer "which is the latest", the question a sequenced
  # folder exists to answer: an index tail read SS00099 while SS00115 was on disk, because the
  # numbering is the sequence and mtime is not. And it made every index position a function of
  # when a file was last touched, so editing one old document reordered the whole file and
  # produced a diff of pure noise. A filename key is stable under edits and puts zero-padded
  # sequences (SS00116 > SS00115) and ISO date prefixes (2026-09-03_x) newest-first for free.
  # KNOWN LIMIT: unpadded numbers sort lexicographically (file10 before file2); pad them.
  #
  # LC_ALL=C, not the ambient locale: byte order is what makes this byte-identical to the
  # Windows sibling's [System.StringComparer]::Ordinal. A locale-aware sort would fold case
  # and punctuation differently on the two platforms and silently desynchronize the indexes.
  files=$(ls -1 "$folder" 2>/dev/null | grep -E '\.md$' | grep -vE '^_index\.md$|^_index_archive\.md$' | LC_ALL=C sort -r)
  total=$(printf '%s\n' "$files" | grep -c . )

  if [ "$total" -le "$INLINE" ]; then
    printf '%s\n' "$files" | while IFS= read -r fn; do
      [ -n "$fn" ] || continue
      printf -- '- %s : %s\n' "$fn" "$(doc_line "$folder/$fn")" >> "$tmp"
    done
  else
    # Newest INLINE stay inline; the rest go to the archive index.
    split=$((total - INLINE))
    newer=$(printf '%s\n' "$files" | head -n "$INLINE")
    older=$(printf '%s\n' "$files" | tail -n "$split")
    arch="$folder/_index_archive.md"
    printf '<!-- GENERATED by phaneslight doc-index. Frozen overflow of _index.md. -->\n# Index archive: %s\n\n' "$name" > "$arch"
    printf '%s\n' "$older" | while IFS= read -r fn; do
      [ -n "$fn" ] || continue
      printf -- '- %s : %s\n' "$fn" "$(doc_line "$folder/$fn")" >> "$arch"
    done
    printf '%s\n' "$newer" | while IFS= read -r fn; do
      [ -n "$fn" ] || continue
      printf -- '- %s : %s\n' "$fn" "$(doc_line "$folder/$fn")" >> "$tmp"
    done
    printf -- '- ... %s older entries collapsed into _index_archive.md\n' "$split" >> "$tmp"
  fi

  mv "$tmp" "$idx"
  n=$(cat "$countfile"); echo $((n + 1)) > "$countfile"
done

written=$(cat "$countfile"); rm -f "$countfile"
echo "doc-index: regenerated $written index file(s)"
exit 0
